feat(TodosTable) добавлен компонент таблицы и запрос к апи
Popshow2011/learnVue pull request #9
Opened 2024-09-04 10:29 UTC by Popshow2011

2024-09-06 05:05 UTC, tamazyanarsen commented
а где запрос к апи?

его нет в изменениях

2024-09-06 05:23 UTC, tamazyanarsen requested changes

2024-09-09 09:45 UTC, tamazyanarsen commented on src/components/TodosTable/Api/FetchTodoList.ts
> +  }
заменить на catch для Promise

2024-09-09 09:45 UTC, tamazyanarsen commented on src/components/TodosTable/TodosTable.vue
> +  }
не используй нигде try-catch без острой необходимости

если это промис, то лучше использовать `.catch`

2024-09-13 09:24 UTC, tamazyanarsen requested changes

2024-09-13 09:24 UTC, tamazyanarsen commented on src/components/TodosTable/TodosTable.vue
> +  todos.value = await fetchTodoList()
аесли вернется ошибка?
может, добавим catch?

2024-09-14 14:45 UTC, Popshow2011 commented on src/components/TodosTable/TodosTable.vue
> +  todos.value = await fetchTodoList()
Да, прошу прощения, торопился, отправляю коммит.

2024-09-14 14:49 UTC, merged